# Generated by Django 5.2.8 on 2025-11-11 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_timeblock'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('greeting_30', 'Saudação 30 min'), ('alert_10', 'Alerta 10 min')], max_length=20)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='appointments.appointment')),
            ],
            options={
                'indexes': [models.Index(fields=['appointment', 'type'], name='appointment_appoint_da3063_idx')],
                'unique_together': {('appointment', 'type')},
            },
        ),
        migrations.CreateModel(
            name='NotificationSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_subscriptions', to='appointments.appointment')),
            ],
            options={
                'indexes': [models.Index(fields=['appointment'], name='appointment_appoint_78631d_idx'), models.Index(fields=['token'], name='appointment_token_87950f_idx')],
                'unique_together': {('appointment', 'token')},
            },
        ),
    ]
