# Generated by Django 5.2.8 on 2025-11-06 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('duration_minutes', models.PositiveIntegerField(default=30)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
