# Generated by Django 5.0.6 on 2025-11-07 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_sale_description_sale_service_withdrawal'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawal',
            name='note',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
